### ISSUE TITLE
Pandas cell with `df_left` and `df_right` does not work for Dynamic Signs

### ISSUE THREAD

**Issue by TomOrth** [chenson2018/APM-Project#1]
I was using the jupyter notebook for the dynamic signs, linked in the readme when I noticed an issue. It seems that the cell where all the data frames are created is not working for me.  The original `pd.merge` line tries to join the frames by their respective times (leftTime and rightTime), however I get the following times:
![Screen Shot 2020-02-09 at 9 26 25 PM](https://user-images.githubusercontent.com/8887487/74116770-febf4100-4b82-11ea-80a8-2a1f17ccb7b7.png)
Due to this, the data frames do not merge together since there is no intersection (I am assuming based on what I read in the pandas documentation).  I was wondering how this could be resolved?

**Comment by chenson2018** [comment]
Hello Tom. I don't recall having any issue of this nature while working on this project. I would check to ensure that the csv files are appropriately stored in your directory. It shouldn't be possible for the data frames to have different row counts, as the information comes from sensor data. If you continue to have this issue, let me know what subject/sign this appears in for you.

**Comment by TomOrth** [comment]
Hello, turns out the issue was that reading the files from a unix file system is different than a windows system which caused the issue.
